# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8877aea57527595d1aed499744e6273f2abbb75d6d804907d5fcaa873ce0bc7deaf61c8d3510e0169da7a53db80eecd618d1b8a53d7effc0674d137ee95020de

test:
  secret_key_base: 17e351f437ef2b595c4ef7fec5b59320cb7a7d2d1f89e58f0d07a14de0a900b4b30460b1a7b7db45a636512824005836747483c25f04ef040840d8129d9a9b92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
